version: '2'
services:
  postgres:
#    image: postgres:9.5
    image: postgres:9.6.6-alpine
    ports:
      - "5432:5432"
#    volumes:
#      - /opt/spmiadata/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"
  mysql:
    image: mysql:5.6.37
    ports:
      - "3306:3306"
#    volumes:
#      - /opt/spmiadata/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "eagle_eye_dev"
#      MYSQL_USER: "eagle"
#      MYSQL_PASSWORD: "eaglepwd"
  redis:
#    image: redis:alpine
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: "10.10.8.11"
      CONSUMER_THREADS: "1"
